# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [92]:
print(np.__version__) 
np.show_config()

1.13.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['libopenblas_v0.2.20_mingwpy', 'libopenblas_v0.2.20_mingwpy']
    library_dirs = ['c:\\opt\\64\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['libopenblas_v0.2.20_mingwpy', 'libopenblas_v0.2.20_mingwpy']
    library_dirs = ['c:\\opt\\64\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['libopenblas_v0.2.20_mingwpy', 'libopenblas_v0.2.20_mingwpy']
    library_dirs = ['c:\\opt\\64\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['libopenblas_v0.2.20_mingwpy', 'libopenblas_v0.2.20_mingwpy']
    library_dirs = ['c:\\opt\\64\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [93]:
vector_np = np.zeros(10)
print(vector_np)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [46]:
vector_np = np.array([1,2,3,4,5], dtype=np.float64)
print(vector_np.size*vector_np.itemsize)

40


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [1]:
import numpy
numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [96]:
vector_np = np.zeros(10)
vector_np[4] = 1
print(vector_np)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [97]:
vector_np = np.arange(10,50)
print(vector_np)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [99]:
vector_np = np.flip(vector_np,-1)
print(vector_np)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [100]:
vector_np = np.arange(9).reshape(3,3)
print(vector_np)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [101]:
vector_np = np.nonzero([1,2,0,0,4,0])
print(vector_np[0])

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [102]:
vector_np = np.eye(3)
print(vector_np)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [103]:
vector_np = np.random.random((3,3,3))
print(vector_np)

[[[ 0.74436125  0.51874147  0.36336865]
  [ 0.45127891  0.13094037  0.26055182]
  [ 0.51715288  0.07177294  0.92853679]]

 [[ 0.17486899  0.0650556   0.21322595]
  [ 0.22866632  0.49992865  0.59771956]
  [ 0.95914741  0.02638095  0.24617701]]

 [[ 0.81037784  0.80174181  0.63280978]
  [ 0.28181018  0.53106524  0.55596796]
  [ 0.74958906  0.11985194  0.52800324]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [104]:
vector_np = np.random.random((10,10))
print(vector_np.max())
print(vector_np.min())

0.998578774595
0.00464572360231


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [105]:
vector_np = np.random.random((10))
print(vector_np)
print(vector_np.mean())

[ 0.51414047  0.68113822  0.46929716  0.54061859  0.31316899  0.44559936
  0.91269333  0.34297377  0.64165206  0.48697556]
0.534825752377


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [109]:
arr = np.zeros((5,5))
vector_np = np.pad(arr, pad_width = 1, mode = 'constant', constant_values = 1)
print(vector_np)

[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [107]:
arr = np.ones((5,5))
vector_np = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(vector_np)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

nan
False
False
nan
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [110]:
vector_np = np.diag(1+np.arange(4), k = -1)
print(vector_np)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [49]:
vector_np = np.zeros((8,8),dtype=int)
vector_np[0::2,1::2], vector_np[1::2,0::2]= 1, 1
print(vector_np)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [50]:
value_np = np.unravel_index(100,(6,7,8))
print(value_np)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [52]:
vector_np = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(vector_np)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [76]:
vector_np = np.array(list(map(lambda row: list(row / np.linalg.norm(row)), np.random.random((5,5)))))
print(vector_np)

[[ 0.87333554  0.1548876   0.10868625  0.38182289  0.23599457]
 [ 0.03589974  0.90316742  0.19890393  0.37107586  0.07576112]
 [ 0.0860523   0.39946141  0.17234637  0.41800041  0.7928417 ]
 [ 0.47224145  0.5481647   0.52045987  0.37753077  0.2511882 ]
 [ 0.69942478  0.0027386   0.49203268  0.49099979  0.16619424]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [82]:
object_np = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(np.array([(2,2,2,0.2), (20,20,20,0.5)], dtype=object_np))

[( 2,  2,  2, 0) (20, 20, 20, 0)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [50]:
vector_np = np.dot(np.ones((5,3)), np.ones((3,2)))
print(vector_np)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [87]:
vector_np = 10*np.random.random(11)
print(vector_np)
vector_np[(3 < vector_np) & (vector_np <= 8)] *= -1
print(vector_np)

[ 4.24023977  7.34127976  9.44023971  5.17181244  0.37952108  9.51722791
  5.18146796  2.06314052  7.86434809  0.93808849  4.08076669]
[-4.24023977 -7.34127976  9.44023971 -5.17181244  0.37952108  9.51722791
 -5.18146796  2.06314052 -7.86434809  0.93808849 -4.08076669]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

nan
0
array([ -2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [122]:
vector_np = np.random.uniform(-10,+10,10)
print(vector_np)
vector_np[vector_np<0] = np.ceil(vector_np[vector_np<0])
vector_np[vector_np>0] = np.floor(vector_np[vector_np>0])
print(vector_np)

[ 7.37678323  0.27177866  8.94803149 -0.70496827  6.73320916  2.40122858
  7.60899526  1.20492788  4.1357053   8.26255034]
[ 7.  0.  8. -0.  6.  2.  7.  1.  4.  8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [51]:
print(np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1]))

[1 3]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [12]:
np.seterr(divide='ignore')
with np.errstate(divide='ignore'):
    # put your code here 

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [143]:
print(np.datetime64('today') + numpy.timedelta64(-1,'D'))
print(np.datetime64('today'))
print(np.datetime64('today') + numpy.timedelta64(1,'D'))

2018-05-19
2018-05-20
2018-05-21


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [144]:
A=2
B=3
C = np.multiply(np.add(A,B), np.divide(np.negative(A), 2))
print(C)

-5.0


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [154]:
vector_np = np.random.uniform(0,10,10)
print (np.trunc(vector_np))
print (vector_np.astype(int).astype(float))
print (np.floor(vector_np))
print (np.ceil(vector_np)-1)
print (vector_np - vector_np%1)

[ 8.  1.  0.  4.  0.  7.  6.  6.  6.  9.]
[ 8.  1.  0.  4.  0.  7.  6.  6.  6.  9.]
[ 8.  1.  0.  4.  0.  7.  6.  6.  6.  9.]
[ 8.  1.  0.  4.  0.  7.  6.  6.  6.  9.]
[ 8.  1.  0.  4.  0.  7.  6.  6.  6.  9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [156]:
vector_np = np.zeros((5,5))
vector_np += np.arange(5)
print(vector_np)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [170]:
def generator():
    for x in range(10):
        yield x
vector_np = np.fromiter(generator(),int,-1)
print(vector_np)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [171]:
vector_np = np.linspace(0,1,12,endpoint=True)[1:-1]
print(vector_np)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [179]:
vector_np = np.random.random(10)
vector_np.sort()
print(vector_np)

[ 0.18493038  0.20911612  0.41987639  0.46056874  0.58816298  0.82679716
  0.90278187  0.95062146  0.96387542  0.96917299]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [186]:
A = np.random.randint(0,2,2)
B = np.random.randint(0,2,2)
print(A)
print(B)
print(np.allclose(A,B))

[0 0]
[0 0]
True


#### 43. Make an array immutable (read-only) (★★☆)

In [188]:
vector_np = np.empty(10)
vector_np.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [189]:
vector_np = np.random.random(10)
print(vector_np)
vector_np[vector_np.argmax()] = 0
print(vector_np)

[ 0.63036215  0.76121445  0.84256795  0.60469689  0.76471127  0.68728008
  0.87631105  0.59677516  0.56600353  0.1282697 ]
[ 0.63036215  0.76121445  0.84256795  0.60469689  0.76471127  0.68728008
  0.          0.59677516  0.56600353  0.1282697 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [34]:
array_np = np.empty((10,10), [('x',float),('y',float)])
array_np['x'], array_np['y'] = np.meshgrid(np.linspace(0,0.9,10),
                             np.linspace(0,0.9,10))
print(array_np)

[[( 0. ,  0. ) ( 0.1,  0. ) ( 0.2,  0. ) ( 0.3,  0. ) ( 0.4,  0. )
  ( 0.5,  0. ) ( 0.6,  0. ) ( 0.7,  0. ) ( 0.8,  0. ) ( 0.9,  0. )]
 [( 0. ,  0.1) ( 0.1,  0.1) ( 0.2,  0.1) ( 0.3,  0.1) ( 0.4,  0.1)
  ( 0.5,  0.1) ( 0.6,  0.1) ( 0.7,  0.1) ( 0.8,  0.1) ( 0.9,  0.1)]
 [( 0. ,  0.2) ( 0.1,  0.2) ( 0.2,  0.2) ( 0.3,  0.2) ( 0.4,  0.2)
  ( 0.5,  0.2) ( 0.6,  0.2) ( 0.7,  0.2) ( 0.8,  0.2) ( 0.9,  0.2)]
 [( 0. ,  0.3) ( 0.1,  0.3) ( 0.2,  0.3) ( 0.3,  0.3) ( 0.4,  0.3)
  ( 0.5,  0.3) ( 0.6,  0.3) ( 0.7,  0.3) ( 0.8,  0.3) ( 0.9,  0.3)]
 [( 0. ,  0.4) ( 0.1,  0.4) ( 0.2,  0.4) ( 0.3,  0.4) ( 0.4,  0.4)
  ( 0.5,  0.4) ( 0.6,  0.4) ( 0.7,  0.4) ( 0.8,  0.4) ( 0.9,  0.4)]
 [( 0. ,  0.5) ( 0.1,  0.5) ( 0.2,  0.5) ( 0.3,  0.5) ( 0.4,  0.5)
  ( 0.5,  0.5) ( 0.6,  0.5) ( 0.7,  0.5) ( 0.8,  0.5) ( 0.9,  0.5)]
 [( 0. ,  0.6) ( 0.1,  0.6) ( 0.2,  0.6) ( 0.3,  0.6) ( 0.4,  0.6)
  ( 0.5,  0.6) ( 0.6,  0.6) ( 0.7,  0.6) ( 0.8,  0.6) ( 0.9,  0.6)]
 [( 0. ,  0.7) ( 0.1,  0.7) ( 0.2,  0.7) ( 0.3,  0.7) (

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [201]:
X = np.random.rand(4)
print(X)
Y = np.random.rand(4)
print(Y)
array_np = 1.0 / np.subtract.outer(X, Y)
print(array_np)

[ 0.55550343  0.15423834  0.06133238  0.3775529 ]
[ 0.83884706  0.53485094  0.28656403  0.36885852]
[[  -3.52928356   48.4203183     3.71830976    5.3577674 ]
 [  -1.46068838   -2.62734334   -7.5571113    -4.65939393]
 [  -1.28614935   -2.1118496    -4.43987324   -3.251756  ]
 [  -2.16781416   -6.3573582    10.99035503  115.01685657]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [208]:
for dtype in [np.int8, np.int32, np.int64]:
   print("min for", dtype, " =", np.iinfo(dtype).min)
   print("max for", dtype, " =",np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print("min for", dtype, " =",np.finfo(dtype).min)
   print("max for", dtype, " =",np.finfo(dtype).max)

min for <class 'numpy.int8'>  = -128
max for <class 'numpy.int8'>  = 127
min for <class 'numpy.int32'>  = -2147483648
max for <class 'numpy.int32'>  = 2147483647
min for <class 'numpy.int64'>  = -9223372036854775808
max for <class 'numpy.int64'>  = 9223372036854775807
min for <class 'numpy.float32'>  = -3.40282e+38
max for <class 'numpy.float32'>  = 3.40282e+38
min for <class 'numpy.float64'>  = -1.79769313486e+308
max for <class 'numpy.float64'>  = 1.79769313486e+308


#### 49. How to print all the values of an array? (★★☆)

In [210]:
np.set_printoptions(threshold=np.nan)
array_np = np.empty((100,100))
print(array_np)

[[  6.43580575e-312   6.43669365e-312   8.30030285e-321               nan
    1.50008929e+248   0.00000000e+000   6.96321522e-077   6.96321522e-077
    6.96321522e-077   6.96321522e-077   6.96321522e-077   6.96321522e-077
    6.96321522e-077   6.96321522e-077   6.96321522e-077   1.12576158e-153
    1.12576158e-153   1.12576158e-153   7.18988912e+140   6.03395497e-154
    6.03395496e-154   6.03395496e-154   6.03395496e-154   6.03395496e-154
    6.03395496e-154   6.03395496e-154   6.03395496e-154   6.03395496e-154
    3.24245662e-086   3.24245679e-086   3.24245679e-086   3.24245679e-086
    1.12576172e-153   1.12576158e-153   1.12576158e-153   1.12576158e-153
    1.12576158e-153   1.12576158e-153   1.12576158e-153   1.12576158e-153
    1.12576158e-153   6.96312200e-077   6.96321522e-077   6.96321522e-077
    6.96321522e-077   3.24263764e-086   3.24245679e-086   3.24245679e-086
    3.24245679e-086   3.24245679e-086   3.24245679e-086   3.24245679e-086
    3.24245679e-086   3.24245679e-086 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [35]:
vector_np = np.random.randint(0,100, 10)
print(vector_np)
scalar_np = np.random.randint(0,100)
print(scalar_np)
print(vector_np[(np.abs(vector_np-scalar_np)).argmin()])

[62 96 50 34 68 25 74 28 80 59]
45
50


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [39]:
array_np = np.empty(5, [ ('position', [ ('x', np.float64, 1),
                                   ('y', np.float64, 1)]),
                    ('color',    [ ('r', np.uint8, 1),
                                   ('g', np.uint8, 1),
                                   ('b', np.uint8, 1)])])
print(array_np)

[((  1.45289446e-311,   3.16202013e-322), ( 0,  0,   0))
 ((  0.00000000e+000,   0.00000000e+000), ( 0,  0,   0))
 ((  1.25718192e-071,   3.57580595e-061), (57, 48, 102))
 ((  1.74087965e+184,   1.20858863e+161), (52, 53, 100))
 ((  7.24641752e-042,   1.00518383e-070), (53, 53,  55))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [42]:
vector_np = np.arange(10, dtype=np.float32)
print(vector_np)
vector_np = vector_np.astype(np.int32, copy=False)
print(vector_np)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

In [ ]:
vector_np = np.genfromtxt("file.txt", delimiter=",")

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [246]:
size = 10
p = 50
array_np = np.zeros((size, size))
np.put(array_np, np.random.choice(range(size*size), p, replace=False),1)
print(array_np)

[[ 1.  1.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  0.  1.  1.  0.  0.  1.]
 [ 1.  0.  1.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  1.  1.  0.  1.  0.  0.  1.]
 [ 0.  1.  1.  1.  1.  1.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  0.  0.  1.  0.  1.]
 [ 0.  1.  1.  1.  1.  0.  1.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  1.  0.  1.  1.  1.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  1.  1.  1.  0.  1.  1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [43]:
array_np = np.random.rand(5, 10)
array_np = array_np.mean(axis=1, keepdims=True)
print(array_np)

[[ 0.48123629]
 [ 0.55927551]
 [ 0.38819222]
 [ 0.38349994]
 [ 0.66558057]]


#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

In [44]:
vector_np = np.random.uniform(0,1,10)
value = 0.5
print(vector_np.flat[np.abs(vector_np - value).argmin()])

0.537521923657


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

SyntaxError: invalid syntax (<ipython-input-45-22c01da4e125>, line 2)

#### 82. Compute a matrix rank (★★★)

In [28]:
Z = np.random.random((6,6))
print(np.linalg.matrix_rank(Z))

6


#### 83. How to find the most frequent value in an array?

In [252]:
Z = np.random.randint(0,10,100)
print(Z)
print(np.bincount(Z).argmax())

[9 9 1 3 1 1 6 2 6 8 8 1 8 2 0 1 7 9 6 6 0 3 4 6 9 6 5 6 0 8 1 6 2 6 6 0 6
 5 2 5 7 6 1 9 5 6 2 6 5 2 6 6 5 5 4 1 1 1 2 3 4 3 2 3 0 2 5 5 1 9 9 9 9 4
 7 1 3 9 3 5 2 4 4 0 6 1 7 0 7 0 9 5 1 6 8 3 6 5 8 2]
6


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [4]:
X=np.random.randint(0,10,10000)
mean = X.mean()
sem = X.std()/np.sqrt(len(X))
print(mean-1.96*sem, mean+1.96*sem)

4.45025705153 4.56294294847
